# Generated by Django 2.1.15 on 2020-06-17 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='past_job',
        ),
    ]
